import {
  ReadinessInput,
  ReadinessResult,
  ReadinessAdvisory,
  HeatmapCell
} from "./types";

/**
 * Build a Markdown steering pack from a completed readiness assessment.
 * Pure string builder — safe to call on the client to trigger a download.
 */
export function buildSteeringPackMarkdown(
  input: ReadinessInput,
  result: ReadinessResult,
  advisory: ReadinessAdvisory,
  heatmap: HeatmapCell[]
): string {
  const date = new Date().toISOString().slice(0, 10);
  const lines: string[] = [];

  lines.push(`# Guidewire Upgrade Readiness — Steering Pack`);
  lines.push("");
  lines.push(`**Generated:** ${date}`);
  lines.push(`**Upgrade:** ${input.currentVersion} → ${input.targetVersion}`);
  lines.push(`**Applications:** ${input.applications.join(", ")}`);
  lines.push("");

  lines.push(`## Readiness summary`);
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`| --- | --- |`);
  lines.push(`| Readiness score | ${result.readinessScore} / 100 |`);
  lines.push(`| Risk level | ${result.riskLevel} |`);
  lines.push(
    `| Recommendation | ${advisory.goNoGoRecommendation.replace("_", " ")} |`
  );
  lines.push(`| Confidence | ${advisory.confidence} |`);
  lines.push(
    `| Advisory source | ${
      advisory.aiGenerated
        ? `Claude (${advisory.model})`
        : "Deterministic fallback"
    } |`
  );
  lines.push("");

  lines.push(`## Executive summary`);
  lines.push("");
  lines.push(advisory.executiveSummary);
  lines.push("");

  lines.push(`## Risk heatmap`);
  lines.push("");
  lines.push(`| Dimension | Risk | Health | Notes |`);
  lines.push(`| --- | --- | --- | --- |`);
  for (const cell of heatmap) {
    lines.push(
      `| ${cell.dimension}${cell.heuristic ? " *(heuristic)*" : ""} | ${
        cell.risk
      } | ${cell.score}/100 | ${cell.note} |`
    );
  }
  lines.push("");

  if (advisory.keyRisks.length) {
    lines.push(`## Key risks`);
    lines.push("");
    lines.push(`| Area | Risk | Business impact |`);
    lines.push(`| --- | --- | --- |`);
    for (const r of advisory.keyRisks) {
      lines.push(`| ${r.area} | ${r.risk} | ${r.businessImpact} |`);
    }
    lines.push("");
  }

  if (result.findings.length) {
    lines.push(`## Rule-based findings`);
    lines.push("");
    for (const f of result.findings) {
      lines.push(`### ${f.area} — ${f.risk}`);
      lines.push(`${f.message}`);
      lines.push(`**Recommendation:** ${f.recommendation}`);
      lines.push("");
    }
  }

  if (advisory.remediationBacklog.length) {
    lines.push(`## Remediation backlog`);
    lines.push("");
    lines.push(`| Priority | Item | Rationale | Effort |`);
    lines.push(`| --- | --- | --- | --- |`);
    for (const r of advisory.remediationBacklog) {
      lines.push(
        `| ${r.priority} | ${r.title} | ${r.rationale} | ${r.estimatedEffort} |`
      );
    }
    lines.push("");
  }

  if (advisory.sprintPlan.length) {
    lines.push(`## Suggested upgrade sprint plan`);
    lines.push("");
    for (const s of advisory.sprintPlan) {
      lines.push(`### ${s.sprint} — ${s.focus}`);
      for (const item of s.items) {
        lines.push(`- ${item}`);
      }
      lines.push("");
    }
  }

  lines.push("---");
  lines.push(
    `_Generated by the Guidewire Upgrade Readiness Assistant. Security and Environments heatmap dimensions are heuristic estimates in this prototype._`
  );
  lines.push("");

  return lines.join("\n");
}
